name: riverpod
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.6.2

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_riverpod: ^1.0.0-dev.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and Firebase Dependencies
  build_runner: ^2.4.15
  firebase_core: ^3.12.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  provider: ^6.1.2
  file_picker: ^9.0.0
  get_it: ^8.0.3
  flutter_spinkit: ^5.2.1
  timeago: ^3.7.0
  flutter_keyboard_visibility: ^6.0.0
  firebase_analytics: ^11.4.2

flutter:
  # Ensures Material Icons font is included
  uses-material-design: true

  # To add assets to your application, add an assets section
  assets:
    - assets/images/

  # For resolution-specific images, see:
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts, use the following structure:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700

# Uncomment the following to enable custom linting
# analyzer:
#   plugins:
#     - custom_lint
